name: Build and publish scan

on:
  workflow_dispatch:
  push:

permissions:
  contents: read

jobs:
  build-and-publish-build-scan:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout sources
      uses: actions/checkout@de0fac2e4500dabe0009e67214ff5f5447ce83dd # v6.0.2
    - name: Setup Gradle
      uses: gradle/actions/setup-gradle@main
      with:
        build-scan-publish: true
        develocity-access-key: "foo"
    - name: Run build
      run: ./gradlew build
